name: code-editor-backend-deploy CI
ON:
    push:
        branches: ["master"]

jobs:
    deploy: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzP
        path: ./*
        remote_path: /home/devil/code-editor-backend
        remote_host: ${{ secrets.DEPLOY_SERVER_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
